### ISSUE TITLE
modify s2i templates and images to work with apache spark 2.3

### ISSUE THREAD

**Issue by tmckayus** [radanalyticsio/oshinko-s2i#206]
Apache Spark 2.3 uses fqdn to communicate with the driver pod. Oshinko s2i needs to add a headless service (in the templates) so that DNS resolution of the driver host name is possible, and it also needs to set the driver host name to that new service in the spark-submit command via the spark.driver.host config.

Additionally, this solution needs to be tested against earlier versions of spark to know whether or not template bundles bundles (resources.yaml) need to be matched against specific versions of spark.

**Comment by tmckayus** [comment]
The service added to the s2i templates will look like this (name is arbitraty as long as the same name is used in the spark-submit command and the name is either well-known or passed to the driver pod in an env-var):

```
- apiVersion: v1
  kind: Service
  metadata:
    name: ${APPLICATION_NAME}-headless
  spec:
    clusterIP: None
    ports:
    - name: driver-rpc-port
      port: 7078
      protocol: TCP
      targetPort: 7078
    - name: blockmanager
      port: 7079
      protocol: TCP
      targetPort: 7079
    selector:
      deploymentConfig: ${APPLICATION_NAME}
    sessionAffinity: None
    type: ClusterIP
```

The start.sh launch script used by the s2is for the standalone case should add this flag to the spark-submit command.

```
--conf spark.driver.host=$APPLICATION_NAME-headless
```
