### ISSUE TITLE
No SPARK_DEFAULT for pyspark-py36-build

### ISSUE THREAD

**Issue by 4n4nd** [radanalyticsio/oshinko-s2i#235]
Is there any way to use a different spark image when I am using the pyspark-py36 build?

I am trying to use radanalyticsio/openshift-spark-py36:latest, but it always defaults to radanalyticsio/openshift-spark:2.3-latest.

I think it could be because it is using an already built executable of oshinko-cli

**Comment by elmiko** [comment]
the primary method for changing the cluster image is to define a `ConfigMap` that contains the image you would like to use and then specify that config to the `DeploymentConfig` when you create your application.

what this might look like on the command line would be like this

1. create the `ConfigMap` by putting the following contents into a file named `oshinko-py36-conf.yaml`
```
  - apiVersion: v1
    kind: ConfigMap
    metadata:
      name: oshinko-py36-conf
    data:
      sparkimage: radanalyticsio/openshift-spark-py36:latest
```

2. create the `ConfigMap` with `oc create -f oshinko-py36-conf.yaml`

3. when spawning your application, make sure to pass the `ConfigMap` name as an environment variable named `OSHINKO_NAMED_CONFIG`. in this example you could do that through the `oc new-app` command by adding `-e OSHINKO_NAMED_CONFIG=oshinko-py36-conf`

this is highly dependent on how you are creating your source-to-image application though.
